version: '3'

services:
  api:
    container_name: k9-backend
    image: node:23.0.0
    working_dir: /app/api
    env_file:
      - .env
    volumes:
      - './api:/app/api'  # Mount mã nguồn của backend
    ports:
      - '3000:3000'  # Truy cập API qua localhost:3000
#    command: ['npm', 'run', 'start:dev']
    command: ['echo', 'No API implemented yet']

  web:
    container_name: Team2_F8_Final-Project
    image: node:23.0.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'  # Mount mã nguồn của frontend
    ports:
      - '5000:3000'
    command: ['npm', 'run', 'dev']

  db:
    container_name: k9-db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'  # Truy cập PostgreSQL qua localhost:4000
    volumes:
      - ./db:/var/lib/postgresql/data  # Lưu trữ dữ liệu của PostgreSQL

volumes:
  db:
    driver: local
